version: 1.2
workflows:
  - name: gfaseWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/gfase.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: bwa-mem2-gfa
    subclass: WDL
    primaryDescriptorPath: /tasks/bwa-mem2.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: combineBams
    subclass: WDL
    primaryDescriptorPath: /tasks/combineBams.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
