version: 1.2
workflows:
  - name: gfaseWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/gfase.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: gfaseTrioWorkflow
    subclass: WDL
    primaryDescriptorPath: /workflows/gfaseTrio.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: bwa-mem2-gfa
    subclass: WDL
    primaryDescriptorPath: /tasks/bwa-mem2.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: combineBams
    subclass: WDL
    primaryDescriptorPath: /tasks/combineBams.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: kmc3
    subclass: WDL
    primaryDescriptorPath: /tasks/kmc.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: dipcall_whatshap_asmgene
    subclass: WDL
    primaryDescriptorPath: /QC/workflows/dipcall_whatshap_asmgene.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: asmgene
    subclass: WDL
    primaryDescriptorPath: /QC/tasks/asmgene.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: whatshapCompare
    subclass: WDL
    primaryDescriptorPath: /QC/tasks/whatshap.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: yak_dipcall_whatshap_asmgene
    subclass: WDL
    primaryDescriptorPath: /QC/workflows/yak_dipcall_whatshap_asmgene.wdl
    authors:
      - name: Melissa Meredith
        email: mmmeredi@ucsc.edu
        orcid: 0000-0001-5736-3193
  - name: gfase_sv_evaluation
    subclass: WDL
    primaryDescriptorPath: /QC/workflows/sv_evaluation.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: gfase_base_qv_evaluation
    subclass: WDL
    primaryDescriptorPath: /QC/workflows/base_qv_evaluation.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: gfase_base_qv_trio_evaluation
    subclass: WDL
    primaryDescriptorPath: /QC/workflows/base_qv_trio_evaluation.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
  - name: evaluate_contacts
    subclass: WDL
    primaryDescriptorPath: /QC/workflows/evaluate_contacts.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
